### ISSUE TITLE
Problem to randomize YKW rom

### ISSUE THREAD

**Issue by GioTheGitFan** [Tiniifan/YKWrandomizer#1]
Hi, I seen your YKW Randomizer and I wanted to try it but I don't have the "right rom". Could you can send me the link of your Discord Channel please ? Like this, I will be able to randomize the YKW rom.

**Comment by Tiniifan** [comment]
Hi. You should read the README.md (available on the first page : https://github.com/Tiniifan/YokaiWatch1Randomizer) before opening an issue because the discord link is written in the README.md

**Comment by GioTheGitFan** [comment]
Excuse me. I didn't Seen !😅😭

**Comment by K1gou** [comment]
![image](https://github.com/Tiniifan/YKWrandomizer/assets/136159291/94fed55a-512d-43fa-9b01-cfab74949290)
Sa me met cela quand je fais le tuto jusqu'au randomizer
