### ISSUE TITLE
this isn't related to the randomizer, but i need help

### ISSUE THREAD

**Issue by skunksecond** [Tiniifan/YKWrandomizer#2]
Would you happen to know where the script file for Yo-Kai Watch 2's Baffle Boards are? I'm working on a mod that translates Shinuchi to Psychic Specters and I need to replace that script file or else you'd have to type the Yo-Kai's name in Japanese.

**Comment by Tiniifan** [comment]
Hi. Please don't open an issue that isn't related to the randomizer.
