### ISSUE TITLE
YKWrandomizer doesn't work on windows 7

### ISSUE THREAD

**Issue by TTOOlink91** [Tiniifan/YKWrandomizer#3]
Hello, I'm trying to randomize ykw 1 and 3 on windows 7 but when I open the required files (yw1_a.fa for ykw 1 and yw_a.fa and yw_lg_fr.fa files for ykw 3) I have an error that prevents me from randomize the games.
If anyone can help me, thank you in advance.

**Comment by Tiniifan** [comment]
Hi, send your error here, without your message error I can't help you

**Comment by TTOOlink91** [comment]
You speak french ?
My pc is in french.

**Comment by Tiniifan** [comment]
Doesn't matter, send the full message error here

**Comment by TTOOlink91** [comment]
Here is the error :
Méthode introuvable : 'Void
System.IO.BinaryReader..ctor(System.IO.Stream.

**Comment by Tiniifan** [comment]
???? It's a joke ? Obviously I can't help you, your error message isn't full

**Comment by TTOOlink91** [comment]
The error message says that an error has occurred and says this.
There is nothing after (System.IO.Stream.

**Comment by Tiniifan** [comment]
Please, next time, when someone asks you for the error message, send the entire text of the error message (usually, there's a button in the dialog box to display the full error message).

**Comment by Tiniifan** [comment]
So, your error is occurring because your .NET Framework package is outdated or nonexistent. 
Download .NET Framework 4.7.2 [here](https://dotnet.microsoft.com/en-us/download/dotnet-framework/net472), and your problem will be resolved. I'm closing this issue.
