### ISSUE TITLE
Scale Randomizer

### ISSUE THREAD

**Issue by Whisperito** [Tiniifan/YKWrandomizer#8]
A randomizer option that would randomize charascales (each entry) to a value between like 0,5 and 5

**Comment by Tiniifan** [comment]
Well, I don't think it's necessary, it makes the randomizer too chaotic, look at the swap models function (when a medium-sized yokai becomes a boss, you can't see anything on the screen), people were already complaining that the bosses were too big in the first version of the randomizer. Even if the randomizer adds some fun functions like "swap models", I think it should remain coherent and not become a catch-with a lot functions irrelevant
